yet_another_microblog/config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"

  devise_for :users
  resources :messages
  resources :users, only: [:update] do
    member do
      get 'profile'
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"

  get '/hello', to: 'home#hello'
end

yet_another_microblog/app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user&.admin?
      can :manage, Message
    else 
      can :read, Message
      can %i[create update destroy], Message, user_id: user.id if user
    end
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

yet_another_microblog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

yet_another_microblog/app/models/following.rb
class Following < ApplicationRecord
  belongs_to :following_user, class_name: 'User', foreign_key: :user_id
  belongs_to :follower, class_name: 'User'
end

yet_another_microblog/app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user

  validates :text, presence: true, length: { in: 5..256 }

  after_create do |message|
    GatherStatsJob.perform_later(message.id)
  end

  def gather_stats
    puts 'gathering stats...'
    sleep 10
    puts 'done!'
  end

  def length
    text.size
  end
end

yet_another_microblog/app/models/settings.rb
class Settings < ApplicationRecord
  belongs_to :user
end

yet_another_microblog/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true

  has_many :messages, dependent: :nullify
  has_one :settings, dependent: :destroy
  has_many :followings
  has_many :followers, through: :followings, class_name: 'User', foreign_key: :follower_id
  has_many :following_users,
           -> (user) { where(followings: {follower_id: user.id}) },
           through: :followings,
           class_name: 'User',
           foreign_key: :follower_id

  has_one_attached :profile_pic

  before_create :do_something
  before_destroy :cleanup

  def hello
    puts 'Hello, world!'
  end

  def admin?
    is_admin
  end

  private

  def do_something
    puts 'Doing something...'
  end

  def cleanup
    puts 'cleaning up...'
  end
end

yet_another_microblog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_locale

  protected

  def set_locale
    I18n.locale = params[:locale] || :en
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

yet_another_microblog/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def hello
    @users = User.all
  end
end

yet_another_microblog/app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, unless: -> { ENV['BENCHMARK'] == 'true' }
  load_and_authorize_resource

  # GET /messages or /messages.json
  def index
    @messages    = Message.includes(:user).order('created_at DESC')
    @new_message = Message.new
  end

  # GET /messages/1 or /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages or /messages.json
  def create
    @message = Message.new(message_params)
    @message.user_id = current_user.id

    respond_to do |format|
      if @message.save
        format.html { redirect_to message_url(@message), notice: "Message was successfully created." }
        format.json { render :show, status: :created, location: @message }
        format.turbo_stream do
          Turbo::StreamsChannel.broadcast_prepend_later_to(
            :messages_stream,
            target: 'messages_list',
            partial: 'messages/message',
            locals: { message: @message }
          )
        end
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
        format.turbo_stream
      end
    end
  end

  # PATCH/PUT /messages/1 or /messages/1.json
  def update
    # Alternatively, instead of load_and_authorize_resource authorize each action explicitly:
    # authorize! :update, @message
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to message_url(@message), notice: "Message was successfully updated." }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1 or /messages/1.json
  def destroy
    @message.destroy!

    respond_to do |format|
      format.html { redirect_to messages_url, notice: "Message was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def message_params
      params.require(:message).permit(:text)
    end
end

yet_another_microblog/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def profile
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to profile_user_url(@user), notice: "User profile was successfully updated."
    else
      render :profile, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_pic)
  end
end

yet_another_microblog/app/helpers/application_helper.rb
module ApplicationHelper
end

yet_another_microblog/app/helpers/messages_helper.rb
module MessagesHelper
end

yet_another_microblog/app/views/home/hello.html.erb
<h2>Hello, students!</h2>

<% @users.each do |user| %>
  <div>
    Name: <%= user.name %> | Email: <%= user.email %>
  </div>
<% end %>

yet_another_microblog/app/views/home/index.html.erb
<h1>Hello, world!</h1>

yet_another_microblog/app/views/layouts/_header.html.erb
<header>
  <nav class="bg-gradient-to-r from-cyan-500 to-indigo-500 rounded px-4 lg:px-6 py-2.5">
    <div class="flex flex-wrap justify-between items-center mx-auto max-w-screen-xl">
      <div class="flex flew-row">
        <%= link_to image_tag('ruby_blob.png', {class: "mr-3 h-6 sm:h-9"}), messages_url %>
        <span class="self-center text-xl font-semibold whitespace-nowrap dark:text-white">
          Yet Another Microblog
        </span>
      </div>
      <div class="flex items-center lg:order-2">
        <%= render 'layouts/logged_in_as' %>
      </div>
    </div>
  </nav>
</header>

yet_another_microblog/app/views/layouts/_logged_in_as.html.erb
<% if current_user %>
  <div class="flex flex-row">
    <div class="p-1">
      Logged in as
      <%= link_to current_user.email, profile_user_path(current_user) %>
    </div>
    <div class="p-1">
      <%= link_to 'Log out', destroy_user_session_path,
        data: { turbo_method: :delete },
        class: 'header-btn'
      %>
    </div>
  </div>
<% else %>
  <%= link_to 'Log in', new_user_session_path, class: 'header-btn' %>
<% end %>

yet_another_microblog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yet Another Microblog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container mx-auto">
      <%= render 'layouts/header' %>

      <p style="color: green"><%= notice %></p>

      <%= yield %>
    </div>
  </body>
</html>

yet_another_microblog/app/views/messages/_form.html.erb
<%= form_with(model: message) do |form| %>
  <% if message.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
        <% message.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label 'Add new message', style: "display: block" %>
    <%= form.text_area :text, rows: "8", class: "w-full", id: 'message_text' %>
    <!-- alternative input definition via plain HTML: -->
    <!--textarea id="message_text" name="message[text]" cols="64" rows="4">
      <%#= message.text %>
    </textarea-->
  </div>

  <div>
    <%= form.submit class: 'btn btn-green' %>
  </div>
<% end %>

yet_another_microblog/app/views/messages/_message.html.erb
<div class="message my-5" id="<%= dom_id message %>">
  <div class="flex flex-row">
    <div class="px-2 font-bold flex flew-row">
      <% if message.user.profile_pic.attached? %>
        <div>
          <%= image_tag url_for(message.user.profile_pic.variant(resize_to_limit: [50, 50])),
                        {class: 'rounded-full'}
          %>
        </div>
      <% end %>
      <div class="px-2">
        <%= message.user&.name %>
      </div>
    </div>
    <div class="px-2 text-gray-500">
      <%= link_to message_path(message), {target: '_top'} do %>
        <%= time_ago_in_words(message.created_at) %> ago
      <% end %>
    </div>
  </div>
  </p>
  <p>
  <div class="px-2"><%= message.text %></div>
  </p>
</div>

yet_another_microblog/app/views/messages/create.turbo_stream.erb
<% if @message.errors.any? %>
  <%= turbo_stream.update "message_form", partial: "form",
                                          locals: { message: @message } %>
<% else %>
  <%= turbo_stream.prepend "messages_list", partial: "message",
                                            locals: { message: @message } %>
  <%= turbo_stream.update "message_form", partial: "form",
                                          locals: { message: Message.new } %>
<% end %>

yet_another_microblog/app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render "form", message: @message %>

<br>

<div>
  <%= link_to "Show this message", @message %> |
  <%= link_to "Back to messages", messages_path %>
</div>

yet_another_microblog/app/views/messages/index.html.erb
<div class="grid grid-cols-3 gap-4">
  <div class="my-2">
    <%= turbo_frame_tag 'message_form' do %>
      <%= render "form", message: @new_message %>
    <% end %>
  </div>

  <div id="messages" class="col-span-2">
    <%= turbo_frame_tag 'messages_list' do %>
      <% @messages.each do |message| %>
        <%= render message %>
      <% end %>
    <% end %>
  </div>
  <%= turbo_stream_from 'messages_stream' %>
</div>

yet_another_microblog/app/views/messages/new.html.erb
<h1>Add a new message</h1>

<%= render "form", message: @message %>

<br>

<div>
  <%= link_to "Back to messages", messages_path %>
</div>

yet_another_microblog/app/views/messages/show.html.erb
<%= render @message %>

<div>
  <% if can?(:update, @message) %>
    <%= link_to "Edit this message", edit_message_path(@message) %> |
  <% end %>
  <%= link_to "Back to messages", messages_path %>

  <% if can?(:destroy, @message) %>
    <%= button_to "Destroy this message", @message, method: :delete %>
  <% end %>
</div>

yet_another_microblog/app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="flex flex-col">
    <div class="py-2">
      <%= form.label 'Name' %>
      <%= form.text_field :name, id: 'user_name' %>
    </div>
    <div class="py-2">
      <%= form.label 'Profile picture' %>
      <% if user.profile_pic.attached? %>
        <%= image_tag url_for(user.profile_pic.variant(resize_to_limit: [50, 50])) %>
      <% end %>
      <%= form.file_field :profile_pic, id: 'profile_pic' %>
    </div>
  </div>

  <div>
    <%= form.submit class: 'btn btn-green' %>
  </div>
<% end %>

yet_another_microblog/app/views/users/profile.html.erb
<%= render "form", user: @user %>

<%= link_to "Back to messages", messages_path %>